language: node_js

node_js: 9

notifications:
  email: false

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: test

      before_install:
        - npm i -g codecov greenkeeper-lockfile

      before_script:
        - npm prune
        - greenkeeper-lockfile-update

      after_script:
        - codecov
        - greenkeeper-lockfile-upload

    - stage: release

      if: branch = master

      script:
        - npx semantic-release
        - |
          mkdir npm-install-test
          cd npm-install-test
          npm init -y
          npm i koa-glitch-keepalive
